import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();
export { LanguageContext };

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    appName: 'Public Distribution System',
    welcome: 'Welcome',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    logout: 'Logout',
    dashboard: 'Dashboard',
    profile: 'Profile',
    settings: 'Settings',
    notifications: 'Notifications',
    distribution: 'Distribution',
    analytics: 'Analytics',
    reports: 'Reports',
    shopManagement: 'Shop Management',
    cardholders: 'Cardholders',
    transactions: 'Transactions',
    forgotPassword: 'Forgot Password?',
    invalidCredentials: 'Invalid email or password',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    beneficiaryRegistration: 'Beneficiary Registration',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    address: 'Address',
    confirmPassword: 'Confirm Password',
    noteManagedAccounts: 'Note: Shop Owner and Village Sarpanch accounts are managed separately.',
    passwordsDoNotMatch: 'Passwords do not match',
    registrationFailed: 'Registration failed. Please try again.',
    shopOwnerDashboardTitle: 'Ration Shop Owner Dashboard',
    totalBeneficiaries: 'Total Beneficiaries',
    pendingCollection: 'Pending Collection',
    sendRationScheduleMessage: 'Send Ration Schedule Message',
    beneficiary: 'Beneficiary',
    scheduleDate: 'Schedule Date',
    scheduleTime: 'Schedule Time',
    message: 'Message',
    sendNotice: 'Send Notice',
    markCollectionStatus: 'Mark Collection Status',
    name: 'Name',
    cardNumber: 'Card Number',
    queueNumber: 'Queue Number',
    status: 'Status',
    action: 'Action',
    role: 'Role',
    collected: 'Collected',
    notCollected: 'Not Collected',
    status_pending: 'Pending',
    status_collected: 'Collected',
    status_not_collected: 'Not Collected',
    defaultScheduleMessage: 'Please collect ration as per schedule.',
    today: 'today',
    messageSentNotice: 'Message sent to {name}: "{message}" for schedule {schedule}.',
    messageSentAllNotice: 'Message sent to all {count} beneficiaries: "{message}" for schedule {schedule}.',
    notificationTarget: 'Notification Target',
    singleBeneficiary: 'Single Beneficiary',
    allBeneficiaries: 'All Beneficiaries',
    userProfile: 'User Profile',
    shopOwnerRole: 'Shop Owner',
    beneficiaryRole: 'Beneficiary',
    sarpanchRole: 'Village Sarpanch',
    shopOwnerProfileName: 'Ration Shop Owner',
    beneficiaryProfileName: 'Ration Beneficiary',
    sarpanchProfileName: 'Village Sarpanch',
    beneficiaryDashboardTitle: 'Ration Beneficiary Dashboard',
    yourDistributionSchedule: 'Your Distribution Schedule',
    date: 'Date',
    time: 'Time',
    shop: 'Shop',
    takeQueueNumber: 'Take Queue Number',
    generateQueueNumber: 'Generate Queue Number',
    yourQueueNumberIs: 'Your queue number is: {number}',
    clickToTakeQueueNumber: 'Click the button to take your queue number.',
    messagesFromShopOwner: 'Messages from Shop Owner',
    beneficiaryMsg1: 'Please bring ration card and Aadhaar copy.',
    beneficiaryMsg2: 'Wheat and rice distribution started for your ward.',
    beneficiaryMsg3: 'Counter closes at 2:00 PM.',
    sarpanchDashboardTitle: 'Village Sarpanch Dashboard',
    totalShops: 'Total Shops',
    openComplaints: 'Open Complaints',
    shopMonitoring: 'Shop Monitoring',
    shopName: 'Shop Name',
    village: 'Village',
    villageName: 'Narshingpur [ Narsewadi ]',
    currentStatus: 'Current Status',
    systemComplaintsOversight: 'System Complaints & Oversight',
    markResolved: 'Mark Resolved',
    state_open: 'Open',
    state_resolved: 'Resolved',
    shop_status_active: 'Active',
    shop_status_review: 'Review',
    complaint_queue_delay: 'Queue delay at Narshingpur shop',
    complaint_marking_error: 'Beneficiary not marked collected correctly',
    addBeneficiaryTitle: 'Add New Beneficiary',
    headOfFamily: 'Head of Family Name',
    rationCardNumber: 'Ration Card Number',
    familyMembersDetails: 'Family Members Details',
    familyMemberLabel: 'Family Member {number}',
    memberName: 'Member Name',
    memberAge: 'Age',
    birthDate: 'Birth Date',
    gender: 'Gender',
    selectGender: 'Select Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    occupation: 'Occupation',
    addFamilyMember: 'Add Family Member',
    removeMember: 'Remove Member',
    submitBeneficiary: 'Save Beneficiary',
    recentlyAddedBeneficiaries: 'Recently Added Beneficiaries',
    totalMembers: 'Total Members',
    noBeneficiaryAdded: 'No beneficiary added yet.',
    beneficiaryAddedSuccess: 'Beneficiary added successfully.',
    allBeneficiariesList: 'All Beneficiaries List',
    villageNameLabel: 'Village',
    rationCardType: 'Ration Card Type',
    cardType_orange: 'Orange',
    cardType_white: 'White',
    cardType_yellow: 'Yellow',
    validationRequiredField: '{field} is required.',
    validationRationCard: 'Ration card number must be 6-20 characters and can include letters, numbers, and hyphen.',
    validationDuplicateRationCard: 'This ration card number is already added.',
    validationAgeRange: 'Age must be between 0 and 120.',
    validationAtLeastOneMember: 'At least one family member is required.',
    headAge: 'Age',
    headBirthDate: 'Birth Date',
    headGender: 'Gender',
    headIncome: 'Income (₹/year)',
    aadhaarNumber: 'Aadhaar Number',
    validationAadhaar: 'Valid 12-digit Aadhaar required',
    complaintSectionTitle: 'Complaint & Feedback Section',
    complaintSubject: 'Subject',
    complaintDescription: 'Description/Details',
    submitComplaint: 'Submit Complaint',
    complaintStatus: 'Status',
    complaintSubmittedSuccess: 'Your complaint has been submitted successfully.',
    complaintFetchFailed: 'Failed to fetch complaints.',
    noComplaintsFound: 'No complaints found.',
    selectSubject: 'Select Subject',
    subject_ration_delay: 'Ration Delay',
    subject_shop_closed: 'Shop Closed',
    subject_quality_issue: 'Quality Issue',
    subject_behavior_issue: 'Behavior Issue',
    subject_other: 'Other',
    'Distribution Overview': 'Distribution Overview',
    'Beneficiaries Per Ward': 'Beneficiaries Per Ward',
    'All Beneficiaries List': 'All Beneficiaries List',
    'No Beneficiary Added': 'No Beneficiary Added',
    'System Complaints Oversight': 'System Complaints Oversight',
    'distributionProgress': 'Distribution Progress',
    'dailyBeneficiaryTraffic': 'Daily Beneficiary Traffic',
    'panchayatDashboard': 'Panchayat Dashboard',
    'totalCardholders': 'Total Cardholders',
    'activeDistributions': 'Active Distributions',
    'completionRate': 'Completion Rate',
    'shopPerformance': 'Shop Performance',
    'recentActivities': 'Recent Activities',
    'efficiency': 'Efficiency',
    'avgWaitTime': 'Avg. Wait Time',
    'stockUtilization': 'Stock Utilization',
    'monthlyTrends': 'Monthly Distribution Trends',
    'generateReport': 'Generate Report',
    'reportTitle': 'Report Title',
    'ownerName': 'Owner Name',
    'area': 'Area',
    'download': 'Download',
    'updateProfile': 'Update Profile',
    'profileUpdatedSuccess': 'Profile updated successfully!'
  },
  hi: {
    appName: 'सार्वजनिक वितरण प्रणाली',
    welcome: 'स्वागत है',
    login: 'लॉगिन',
    register: 'पंजीकरण',
    email: 'ईमेल',
    password: 'पासवर्ड',
    logout: 'लॉग आउट',
    dashboard: 'डैशबोर्ड',
    profile: 'प्रोफ़ाइल',
    settings: 'सेटिंग्स',
    notifications: 'सूचनाएं',
    distribution: 'वितरण',
    analytics: 'विश्लेषण',
    reports: 'रिपोर्ट',
    shopManagement: 'दुकान प्रबंधन',
    cardholders: 'कार्डधारक',
    transactions: 'लेनदेन',
    forgotPassword: 'पासवर्ड भूल गए?',
    invalidCredentials: 'ईमेल या पासवर्ड गलत है',
    dontHaveAccount: 'क्या आपका खाता नहीं है?',
    alreadyHaveAccount: 'क्या आपका पहले से खाता है?',
    beneficiaryRegistration: 'लाभार्थी पंजीकरण',
    fullName: 'पूरा नाम',
    phoneNumber: 'फोन नंबर',
    address: 'पता',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    noteManagedAccounts: 'नोट: दुकान मालिक और ग्राम सरपंच के खाते अलग से प्रबंधित किए जाते हैं।',
    passwordsDoNotMatch: 'पासवर्ड मेल नहीं खा रहे हैं',
    registrationFailed: 'पंजीकरण असफल रहा। कृपया फिर प्रयास करें।',
    shopOwnerDashboardTitle: 'राशन दुकान मालिक डैशबोर्ड',
    totalBeneficiaries: 'कुल लाभार्थी',
    pendingCollection: 'लंबित वितरण',
    sendRationScheduleMessage: 'राशन समय-सारणी संदेश भेजें',
    beneficiary: 'लाभार्थी',
    scheduleDate: 'वितरण तिथि',
    scheduleTime: 'वितरण समय',
    message: 'संदेश',
    sendNotice: 'सूचना भेजें',
    markCollectionStatus: 'प्राप्ति स्थिति दर्ज करें',
    name: 'नाम',
    cardNumber: 'कार्ड नंबर',
    queueNumber: 'क्यू नंबर',
    status: 'स्थिति',
    action: 'कार्रवाई',
    role: 'भूमिका',
    collected: 'प्राप्त',
    notCollected: 'प्राप्त नहीं',
    status_pending: 'लंबित',
    status_collected: 'प्राप्त',
    status_not_collected: 'प्राप्त नहीं',
    defaultScheduleMessage: 'कृपया तय समय के अनुसार राशन प्राप्त करें।',
    today: 'आज',
    messageSentNotice: '{name} को संदेश भेजा गया: "{message}" समय-सारणी {schedule} के लिए।',
    messageSentAllNotice: 'सभी {count} लाभार्थियों को संदेश भेजा गया: "{message}" समय-सारणी {schedule} के लिए।',
    notificationTarget: 'सूचना लक्ष्य',
    singleBeneficiary: 'एक लाभार्थी',
    allBeneficiaries: 'सभी लाभार्थी',
    userProfile: 'यूजर प्रोफ़ाइल',
    shopOwnerRole: 'दुकान मालिक',
    beneficiaryRole: 'लाभार्थी',
    sarpanchRole: 'ग्राम सरपंच',
    shopOwnerProfileName: 'राशन दुकान मालिक',
    beneficiaryProfileName: 'राशन लाभार्थी',
    sarpanchProfileName: 'ग्राम सरपंच',
    beneficiaryDashboardTitle: 'राशन लाभार्थी डैशबोर्ड',
    yourDistributionSchedule: 'आपकी वितरण समय-सारणी',
    date: 'तिथि',
    time: 'समय',
    shop: 'दुकान',
    takeQueueNumber: 'क्यू नंबर लें',
    generateQueueNumber: 'क्यू नंबर बनाएं',
    yourQueueNumberIs: 'आपका क्यू नंबर है: {number}',
    clickToTakeQueueNumber: 'क्यू नंबर लेने के लिए बटन दबाएं।',
    messagesFromShopOwner: 'दुकान मालिक के संदेश',
    beneficiaryMsg1: 'कृपया राशन कार्ड और आधार की प्रति साथ लाएं।',
    beneficiaryMsg2: 'आपके वार्ड के लिए गेहूं और चावल का वितरण शुरू हो गया है।',
    beneficiaryMsg3: 'काउंटर दोपहर 2:00 बजे बंद होगा।',
    sarpanchDashboardTitle: 'ग्राम सरपंच डैशबोर्ड',
    totalShops: 'कुल दुकानें',
    openComplaints: 'खुली शिकायतें',
    shopMonitoring: 'दुकान निगरानी',
    shopName: 'दुकान का नाम',
    village: 'गांव',
    villageName: 'नरसिंगपूर [ नरसेवाडी ]',
    currentStatus: 'वर्तमान स्थिति',
    systemComplaintsOversight: 'सिस्टम शिकायतें और निगरानी',
    markResolved: 'समाधान चिह्नित करें',
    state_open: 'खुली',
    state_resolved: 'समाधान',
    shop_status_active: 'सक्रिय',
    shop_status_review: 'समीक्षा',
    complaint_queue_delay: 'नरसिंहपुर दुकान पर क्यू में देरी',
    complaint_marking_error: 'लाभार्थी की प्राप्ति स्थिति गलत दर्ज हुई',
    addBeneficiaryTitle: 'नया लाभार्थी जोड़ें',
    headOfFamily: 'परिवार प्रमुख का नाम',
    rationCardNumber: 'राशन कार्ड नंबर',
    familyMembersDetails: 'परिवार के सदस्यों का विवरण',
    familyMemberLabel: 'परिवार सदस्य {number}',
    memberName: 'सदस्य का नाम',
    memberAge: 'आयु',
    birthDate: 'जन्म तिथि',
    gender: 'लिंग',
    selectGender: 'लिंग चुनें',
    male: 'पुरुष',
    female: 'महिला',
    other: 'अन्य',
    occupation: 'व्यवसाय',
    addFamilyMember: 'परिवार सदस्य जोड़ें',
    removeMember: 'सदस्य हटाएं',
    submitBeneficiary: 'लाभार्थी सहेजें',
    recentlyAddedBeneficiaries: 'हाल ही में जोड़े गए लाभार्थी',
    totalMembers: 'कुल सदस्य',
    noBeneficiaryAdded: 'अभी तक कोई लाभार्थी नहीं जोड़ा गया।',
    beneficiaryAddedSuccess: 'लाभार्थी सफलतापूर्वक जोड़ा गया।',
    allBeneficiariesList: 'सभी लाभार्थियों की सूची',
    villageNameLabel: 'गांव',
    rationCardType: 'राशन कार्ड का प्रकार',
    cardType_orange: 'नारंगी (Orange)',
    cardType_white: 'सफेद (White)',
    cardType_yellow: 'पीला (Yellow)',
    validationRequiredField: '{field} आवश्यक है।',
    validationRationCard: 'राशन कार्ड नंबर 6-20 अक्षरों का होना चाहिए और इसमें अक्षर, संख्या या हाइफ़न हो सकता है।',
    validationDuplicateRationCard: 'यह राशन कार्ड नंबर पहले से जोड़ा गया है।',
    validationAgeRange: 'आयु 0 से 120 के बीच होनी चाहिए।',
    validationAtLeastOneMember: 'कम से कम एक परिवार सदस्य आवश्यक है।',
    headAge: 'आयु',
    headBirthDate: 'जन्म तिथि',
    headGender: 'लिंग',
    headIncome: 'आय (₹/वर्ष)',
    aadhaarNumber: 'आधार नंबर',
    validationAadhaar: 'मान्य 12-अंकीय आधार आवश्यक है',
    complaintSectionTitle: 'शिकायत और प्रतिक्रिया अनुभाग',
    complaintSubject: 'विषय',
    complaintDescription: 'विवरण / जानकारी',
    submitComplaint: 'शिकायत दर्ज करें',
    complaintStatus: 'स्थिति',
    complaintSubmittedSuccess: 'आपकी शिकायत सफलतापूर्वक दर्ज कर ली गई है।',
    complaintFetchFailed: 'शिकायतें प्राप्त करने में विफल।',
    noComplaintsFound: 'कोई शिकायत नहीं मिली।',
    selectSubject: 'विषय चुनें',
    subject_ration_delay: 'राशन में देरी',
    subject_shop_closed: 'दुकान बंद होना',
    subject_quality_issue: 'गुणवत्ता संबंधी समस्या',
    subject_behavior_issue: 'व्यवहार संबंधी मुद्दा',
    subject_other: 'अन्य',
    'Distribution Overview': 'वितरण अवलोकन',
    'Beneficiaries Per Ward': 'वार्ड वार लाभार्थी',
    'All Beneficiaries List': 'सभी लाभार्थियों की सूची',
    'No Beneficiary Added': 'कोई लाभार्थी नहीं जोड़ा गया',
    'System Complaints Oversight': 'प्रणाली शिकायत निगरानी',
    'distributionProgress': 'वितरण प्रगति',
    'dailyBeneficiaryTraffic': 'दैनिक लाभार्थी आगमन',
    'panchayatDashboard': 'पंचायत डैशबोर्ड',
    'totalCardholders': 'कुल कार्डधारक',
    'activeDistributions': 'सक्रिय वितरण',
    'completionRate': 'पूर्णता दर',
    'shopPerformance': 'दुकान का प्रदर्शन',
    'recentActivities': 'हाल की गतिविधियां',
    'efficiency': 'दक्षता',
    'avgWaitTime': 'औसत प्रतीक्षा समय',
    'stockUtilization': 'स्टॉक उपयोग',
    'monthlyTrends': 'मासिक वितरण रुझान',
    'generateReport': 'रिपोर्ट तैयार करें',
    'reportTitle': 'रिपोर्ट का शीर्षक',
    'ownerName': 'मालिक का नाम',
    'area': 'क्षेत्र',
    'download': 'डाउनलोड',
    'updateProfile': 'प्रोफ़ाइल अपडेट करें',
    'profileUpdatedSuccess': 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!'
  },
  mr: {
    appName: 'सार्वजनिक वितरण प्रणाली',
    welcome: 'स्वागत आहे',
    login: 'लॉगिन',
    register: 'नोंदणी',
    email: 'ईमेल',
    password: 'पासवर्ड',
    logout: 'लॉग आउट',
    dashboard: 'डॅशबोर्ड',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्ज',
    notifications: 'सूचना',
    distribution: 'वितरण',
    analytics: 'विश्लेषण',
    reports: 'अहवाल',
    shopManagement: 'दुकान व्यवस्थापन',
    cardholders: 'कार्डधारक',
    transactions: 'व्यवहार',
    forgotPassword: 'पासवर्ड विसरलात?',
    invalidCredentials: 'ईमेल किंवा पासवर्ड चुकीचा आहे',
    dontHaveAccount: 'तुमचे खाते नाही का?',
    alreadyHaveAccount: 'तुमचे आधीपासून खाते आहे का?',
    beneficiaryRegistration: 'लाभार्थी नोंदणी',
    fullName: 'पूर्ण नाव',
    phoneNumber: 'फोन नंबर',
    address: 'पत्ता',
    confirmPassword: 'पासवर्ड पुष्टी करा',
    noteManagedAccounts: 'टीप: दुकान मालक आणि ग्राम सरपंच खाती स्वतंत्रपणे व्यवस्थापित केली जातात.',
    passwordsDoNotMatch: 'पासवर्ड जुळत नाहीत',
    registrationFailed: 'नोंदणी अयशस्वी झाली. कृपया पुन्हा प्रयत्न करा.',
    shopOwnerDashboardTitle: 'रेशन दुकान मालक डॅशबोर्ड',
    totalBeneficiaries: 'एकूण लाभार्थी',
    pendingCollection: 'प्रलंबित वितरण',
    sendRationScheduleMessage: 'रेशन वेळापत्रक संदेश पाठवा',
    beneficiary: 'लाभार्थी',
    scheduleDate: 'वितरण तारीख',
    scheduleTime: 'वितरण वेळ',
    message: 'संदेश',
    sendNotice: 'सूचना पाठवा',
    markCollectionStatus: 'स्वीकृती स्थिती नोंदवा',
    name: 'नाव',
    cardNumber: 'कार्ड क्रमांक',
    queueNumber: 'रांग क्रमांक',
    status: 'स्थिती',
    action: 'क्रिया',
    role: 'भूमिका',
    collected: 'स्वीकृत',
    notCollected: 'स्वीकृत नाही',
    status_pending: 'प्रलंबित',
    status_collected: 'स्वीकृत',
    status_not_collected: 'स्वीकृत नाही',
    defaultScheduleMessage: 'कृपया वेळापत्रकानुसार रेशन घ्या.',
    today: 'आज',
    messageSentNotice: '{name} यांना संदेश पाठवला: "{message}" वेळापत्रक {schedule} साठी.',
    messageSentAllNotice: 'सर्व {count} लाभार्थ्यांना संदेश पाठवला: "{message}" वेळापत्रक {schedule} साठी.',
    notificationTarget: 'सूचना लक्ष्य',
    singleBeneficiary: 'एक लाभार्थी',
    allBeneficiaries: 'सर्व लाभार्थी',
    userProfile: 'वापरकर्ता प्रोफाइल',
    shopOwnerRole: 'दुकान मालक',
    beneficiaryRole: 'लाभार्थी',
    sarpanchRole: 'ग्राम सरपंच',
    shopOwnerProfileName: 'रेशन दुकान मालक',
    beneficiaryProfileName: 'रेशन लाभार्थी',
    sarpanchProfileName: 'ग्राम सरपंच',
    beneficiaryDashboardTitle: 'रेशन लाभार्थी डॅशबोर्ड',
    yourDistributionSchedule: 'तुमचे वितरण वेळापत्रक',
    date: 'तारीख',
    time: 'वेळ',
    shop: 'दुकान',
    takeQueueNumber: 'रांग क्रमांक घ्या',
    generateQueueNumber: 'रांग क्रमांक तयार करा',
    yourQueueNumberIs: 'तुमचा रांग क्रमांक आहे: {number}',
    clickToTakeQueueNumber: 'रांग क्रमांक घेण्यासाठी बटन दाबा.',
    messagesFromShopOwner: 'दुकान मालकाचे संदेश',
    beneficiaryMsg1: 'कृपया रेशन कार्ड आणि आधारची प्रत आणा.',
    beneficiaryMsg2: 'तुमच्या विभागासाठी गहू आणि तांदूळ वितरण सुरू झाले आहे.',
    beneficiaryMsg3: 'काउंटर दुपारी 2:00 वाजता बंद होईल.',
    sarpanchDashboardTitle: 'ग्राम सरपंच डॅशबोर्ड',
    totalShops: 'एकूण दुकाने',
    openComplaints: 'उघड्या तक्रारी',
    shopMonitoring: 'दुकान देखरेख',
    shopName: 'दुकानाचे नाव',
    village: 'गाव',
    villageName: 'नरसिंगपूर [ नरसेवाडी ]',
    currentStatus: 'सध्याची स्थिती',
    systemComplaintsOversight: 'प्रणाली तक्रारी आणि देखरेख',
    markResolved: 'निकाली काढा',
    state_open: 'उघडी',
    state_resolved: 'निकाली',
    shop_status_active: 'सक्रिय',
    shop_status_review: 'पडताळणी',
    complaint_queue_delay: 'नरसिंहपूर दुकानात रांगेत विलंब',
    complaint_marking_error: 'लाभार्थीची स्वीकृती स्थिती चुकीची नोंदली गेली',
    addBeneficiaryTitle: 'नवीन लाभार्थी जोडा',
    headOfFamily: 'कुटुंब प्रमुखाचे नाव',
    rationCardNumber: 'रेशन कार्ड क्रमांक',
    familyMembersDetails: 'कुटुंब सदस्यांची माहिती',
    familyMemberLabel: 'कुटुंब सदस्य {number}',
    memberName: 'सदस्याचे नाव',
    memberAge: 'वय',
    birthDate: 'जन्मतारीख',
    gender: 'लिंग',
    selectGender: 'लिंग निवडा',
    male: 'पुरुष',
    female: 'महिला',
    other: 'इतर',
    occupation: 'व्यवसाय',
    addFamilyMember: 'कुटुंब सदस्य जोडा',
    removeMember: 'सदस्य काढा',
    submitBeneficiary: 'लाभार्थी जतन करा',
    recentlyAddedBeneficiaries: 'अलीकडे जोडलेले लाभार्थी',
    totalMembers: 'एकूण सदस्य',
    noBeneficiaryAdded: 'अजून कोणताही लाभार्थी जोडलेला नाही.',
    beneficiaryAddedSuccess: 'लाभार्थी यशस्वीरित्या जोडला गेला.',
    allBeneficiariesList: 'सर्व लाभार्थ्यांची यादी',
    villageNameLabel: 'गाव',
    rationCardType: 'रेशन कार्डचा प्रकार',
    cardType_orange: 'केशरी (Orange)',
    cardType_white: 'पांढरा (White)',
    cardType_yellow: 'पिवळा (Yellow)',
    validationRequiredField: '{field} आवश्यक आहे।',
    validationRationCard: 'रेशन कार्ड क्रमांक 6-20 वर्णांचा असावा आणि त्यात अक्षरे, अंक किंवा हायफन असू शकतो.',
    validationDuplicateRationCard: 'हा रेशन कार्ड क्रमांक आधीच जोडलेला आहे.',
    validationAgeRange: 'वय 0 ते 120 दरम्यान असावे।',
    validationAtLeastOneMember: 'किमान एक कुटुंब सदस्य आवश्यक आहे।',
    headAge: 'वय',
    headBirthDate: 'जन्मतारीख',
    headGender: 'लिंग',
    headIncome: 'उत्पन्न (₹/वर्ष)',
    aadhaarNumber: 'आधार क्रमांक',
    validationAadhaar: 'वैध 12-अंकी आधार आवश्यक आहे',
    complaintSectionTitle: 'तक्रार आणि अभिप्राय विभाग',
    complaintSubject: 'विषय',
    complaintDescription: 'वर्णन / तपशील',
    submitComplaint: 'तक्रार सबमिट करा',
    complaintStatus: 'स्थिती',
    complaintSubmittedSuccess: 'तुमची तक्रार यशस्वीरित्या सबमिट केली गेली आहे।',
    complaintFetchFailed: 'तक्रारी मिळवण्यात अपयश।',
    noComplaintsFound: 'कोणतीही तक्रार आढळली नाही।',
    selectSubject: 'विषय निवडा',
    subject_ration_delay: 'रेशन उशीर',
    subject_shop_closed: 'दुकान बंद',
    subject_quality_issue: 'गुणवत्ता समस्या',
    subject_behavior_issue: 'वर्तन समस्या',
    subject_other: 'इतर',
    'Distribution Overview': 'वितरण आढावा',
    'Beneficiaries Per Ward': 'वॉर्डनुसार लाभार्थी',
    'All Beneficiaries List': 'सर्व लाभार्थ्यांची यादी',
    'No Beneficiary Added': 'कोणताही लाभार्थी जोडलेला नाही',
    'System Complaints Oversight': 'प्रणाली तक्रार देखरेख',
    'distributionProgress': 'वितरण प्रगती',
    'dailyBeneficiaryTraffic': 'दैनिक लाभार्थी रहदारी',
    'panchayatDashboard': 'पंचायत डॅशबोर्ड',
    'totalCardholders': 'एकूण कार्डधारक',
    'activeDistributions': 'सक्रिय वितरण',
    'completionRate': 'पूर्णता दर',
    'shopPerformance': 'दुकान कामगिरी',
    'recentActivities': 'अलीकडील क्रियाकलाप',
    'efficiency': 'कार्यक्षमता',
    'avgWaitTime': 'सरासरी प्रतीक्षा वेळ',
    'stockUtilization': 'स्टॉक वापर',
    'monthlyTrends': 'मासिक वितरण ट्रेंड',
    'generateReport': 'अहवाल तयार करा',
    'reportTitle': 'अहवालाचे शीर्षक',
    'ownerName': 'मालकाचे नाव',
    'area': 'क्षेत्र',
    'download': 'डाउनलोड',
    'updateProfile': 'प्रोफाइल अपडेट करा',
    'profileUpdatedSuccess': 'प्रोफाइल यशस्वीरित्या अपडेट झाली!'
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const storedLanguage = localStorage.getItem('language');
    if (storedLanguage && translations[storedLanguage]) {
      setLanguage(storedLanguage);
    }
  }, []);

  const t = (key, params = {}) => {
    const baseText = translations[language]?.[key] || translations.en[key] || key;
    return Object.keys(params).reduce(
      (result, paramKey) => result.replace(new RegExp(`{${paramKey}}`, 'g'), params[paramKey]),
      baseText
    );
  };

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
      localStorage.setItem('language', lang);
    }
  };

  const value = {
    language,
    changeLanguage,
    t
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
